### ISSUE TITLE
Problem with Cognate Set Merger-Function

### ISSUE THREAD

**Issue by CasFre** [lingdb/CoBL#294]
Hello @runjak,
I tried to merge cognate sets A and E for the meaning "shadow" (http://www.cobl.info/cognate/5058/ and http://www.cobl.info/cognate/5210/) several times, but I always get the following notification:
![problem with merger](https://cloud.githubusercontent.com/assets/17431124/17622740/7d77d38e-609c-11e6-8efd-043b802d42ad.png)

Is that only a temporary problem or is it a more general one?

**Comment by runjak** [comment]
Hi @CasFre I'll have a look in a minute.

**Comment by runjak** [comment]
Interesting - this worked on my machine - I'll copy the current server state of the database to see if it behaves the same.

**Comment by CasFre** [comment]
Did you do something to this problem in the meantime?
Merging cognate sets was possible today for Roland, Matthew and me.

**Comment by cormacanderson** [comment]
This morning it's not working for me. I think this is work looking into.

**Comment by runjak** [comment]
This appears to be an unexpected problem relating to a `CognateClassCitation`.
From the server logs:

```
[2016-08-16 16:13:52,999] ERROR Problem merging CognateClasses in view_cognateclasses.
Traceback (most recent call last):
  File "/CoBL/ielex/views.py", line 1480, in view_cognateclasses
    cognate_class_id=newC.id)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/query.py", line 563, in update
    rows = query.get_compiler(self.db).execute_sql(CURSOR)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 1062, in execute_sql
    cursor = super(SQLUpdateCompiler, self).execute_sql(result_type)
  File "/usr/local/lib/python2.7/dist-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python2.7/dist-packages/django/db/utils.py", line 98, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
IntegrityError: duplicate key value violates unique constraint "lexicon_cognateclasscitation_cognate_class_id_4bf01279_uniq"
DETAIL:  Key (cognate_class_id, source_id)=(6153, 66) already exists.
```

The problem here is that when merging cognate classes I always try to move the existing citations to the new class. But each class can have only one citation for each source. So in cases where two classes have a common source cited this will currently lead to problems.
The obvious fix here will be to identify these cases and merge only the description texts of such citations instead of having two citations for the same source.
